=== agungdeomartha/Tugas-XSD-Praktikum/JasaSewaKamera.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="sewakamera">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="alamat"/>
                <xs:element ref="denda"/>
                <xs:element ref="durasi"/>
                <xs:element ref="harga"/>
                <xs:element ref="id"/>
                <xs:element ref="jeniskamera"/>
                <xs:element ref="peminjam"/>
                <xs:element ref="tglkembali"/>
                <xs:element ref="tglsewa"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="alamat" type="xs:NCName"/>
    <xs:element name="denda" type="xs:integer"/>
    <xs:element name="durasi" type="xs:string"/>
    <xs:element name="harga">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="harga" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="id" type="xs:integer"/>
    <xs:element name="jeniskamera" type="xs:string"/>
    <xs:element name="peminjam" type="xs:NCName"/>
    <xs:element name="tglkembali" type="xs:string"/>
    <xs:element name="tglsewa" type="xs:string"/>
</xs:schema>

=== agungdeomartha/Tugas-XSD-Praktikum/JasaSewaKamera.xml
<?xml version="1.0" encoding="UTF-8"?>
<sewakamera xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="JasaSewaKamera.xsd">
	
	<id>11</id>
	<peminjam>Dhea</peminjam>
	<alamat>Subang</alamat>
	<jeniskamera>ACTION CAM</jeniskamera>
	<harga harga="100 ribu perhari">100</harga>
	<tglkembali>10 januari</tglkembali>
	<tglsewa>9 januari</tglsewa>
	<durasi>1 hari</durasi>
	<denda>0</denda>
	
	<id>12</id>
	<peminjam>Yusri</peminjam>
	<alamat>Bogor</alamat>
	<jeniskamera>DSLR</jeniskamera>
	<harga harga="100 ribu perhari">150</harga>
	<tglkembali>12 januari</tglkembali>
	<tglsewa>11 januari</tglsewa>
	<durasi>1 hari</durasi>
	<denda>0</denda>
	
	<id>13</id>
	<peminjam>Sabda</peminjam>
	<alamat>Tasik</alamat>
	<jeniskamera>ACTION CAM</jeniskamera>
	<harga harga="100 ribu perhari">100</harga>
	<tglkembali>10 februari</tglkembali>
	<tglsewa>9 februari</tglsewa>
	<durasi>1 hari</durasi>
	<denda>0</denda>
	
	<id>14</id>
	<peminjam>Diana</peminjam>
	<alamat>Ciasmis</alamat>
	<jeniskamera>Drone</jeniskamera>
	<harga harga="100 ribu perhari">100</harga>
	<tglkembali>10 januari</tglkembali>
	<tglsewa>9 januari</tglsewa>
	<durasi>1 hari</durasi>
	<denda>0</denda>
	
	<id>15</id>
	<peminjam>Dana</peminjam>
	<alamat>Aceh</alamat>
	<jeniskamera>Mirrorless CAM</jeniskamera>
	<harga harga="100 ribu perhari">100</harga>
	<tglkembali>10 februari</tglkembali>
	<tglsewa>9 februari</tglsewa>
	<durasi>1 hari</durasi>
	<denda>0</denda>
	
	
</sewakamera>
